import tkinter as tk
from tkinter import *
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

root = tk.Tk()
root.geometry("1920x1080")
root.resizable(True,True)
root.title("Covid-19 cases")
root.configure(background="#3BF6E4")

url = "https://api.covid19india.org/csv/latest/state_wise.csv"
state_csv = pd.read_csv(url)

df=pd.DataFrame(state_csv)
df.drop(0,axis=0,inplace=True)

def Maharashtra():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Maharashtra")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][21]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][21]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][21]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][21]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def tamilnadu():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("TamilNadu")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][32]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][32]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][32]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][32]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def delhi():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Delhi")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][9]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][9]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][9]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][9]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
def gujrat():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Gujrat")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][11]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][11]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][11]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][11]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def karnatka():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Karnatka")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][16]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][16]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][16]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][16]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def up():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("UttarPradesh")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][35]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][35]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][35]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][35]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def telangana():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Telangana")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][33]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][33]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][33]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][33]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def andhrapradesh():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("AndhraPradesh")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][2]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][2]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][2]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][2]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def wb():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("WestBengal")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][37]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][37]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][37]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][37]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def rajasthan():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Rajasthan")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][29]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][29]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][29]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][29]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def haryana():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Haryana")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][12]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][12]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][12]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][12]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def bihar():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Bihar")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][5]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][5]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][5]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][5]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def mp():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Madhya Pradesh")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][20]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][20]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][20]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][20]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def assam():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Assam")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][4]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][4]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][4]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][4]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def odisha():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Odisha")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][26]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][26]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][26]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][26]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def jk():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("J&K")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][14]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][14]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][14]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][14]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def punjab():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Punjab")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][28]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][28]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][28]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][28]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def kerala():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Kerala")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][17]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][17]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][17]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][17]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def chattisgarh():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Chattisgarh")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][7]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][7]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][7]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][7]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def jharkhand():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Jharkhand")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][15]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][15]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][15]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][15]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def uttarakhand():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Uttarakhand")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][36]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][36]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][36]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][36]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def goa():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Goa")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][10]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][10]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][10]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][10]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def su():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("State Unasignned")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][31]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][31]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][31]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][31]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def tripura():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Tripura")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][34]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][34]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][34]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][34]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def manipur():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Manipur")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][22]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][22]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][22]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][22]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def puducherry():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Puducherry")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][27]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][27]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][27]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][27]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def himachal():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Himachal")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][13]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][13]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][13]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][13]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def ladakh():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Ladakh")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][18]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][18]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][18]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][18]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def nagaland():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Nagaland")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][25]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][25]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][25]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][25]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def chandigarh():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Chandigarh")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][6]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][6]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][6]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][6]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def DD():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Daman&diu")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][8]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][8]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][8]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][8]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def arunachal():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Arunachal Pradesh")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][3]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][3]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][3]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][3]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def meghalaya():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Meghalaya")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][23]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][23]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][23]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][23]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def mizoram():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Mizoram")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][24]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][24]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][24]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][24]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def anl():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Andoman & NL")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][1]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][1]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][1]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][1]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def sikkim():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Sikkim")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][30]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][30]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][30]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][30]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def lk():
    win=Toplevel()
    win.geometry("250x250")
    win.resizable(False,False)
    win.title("Lakshadweep")
    win.configure(background="#3BF6E4")
    confirmed = StringVar()
    confirmed.set("Confirmed till Now : {} ".format(state_csv["Confirmed"][19]))
    directionlb = Label(win,textvariable = confirmed)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Active till Now : {} ".format(state_csv["Active"][19]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Recovered = StringVar()
    Recovered.set("Recovered till Now : {}".format(state_csv["Recovered"][19]))
    directionlb = Label(win,textvariable = Recovered)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()
    Active = StringVar()
    Active.set("Deaths till Now : {} ".format(state_csv["Deaths"][19]))
    directionlb = Label(win,textvariable = Active)
    directionlb.configure(background="#3BF6E4")
    directionlb.pack()

def cgraph():
    win=Toplevel()
    win.geometry("1000x250")
    win.resizable(False,False)
    win.title("Graph of Confirmed Cases")
    win.configure(background="#3BF6E4")
    x=df["State_code"]
    y=df["Confirmed"]
    fig=plt.Figure(figsize=(50,50),dpi=100)
    fig.add_subplot(111).bar(x,y)
    chart=FigureCanvasTkAgg(fig,win)
    chart.get_tk_widget().pack()


def rgraph():
    win=Toplevel()
    win.geometry("1000x250")
    win.resizable(False,False)
    win.title("Graph of recovered Cases")
    win.configure(background="#3BF6E4")
    x=df["State_code"]
    y=df["Recovered"]
    fig=plt.Figure(figsize=(50,50),dpi=100)
    fig.add_subplot(111).bar(x,y)
    chart=FigureCanvasTkAgg(fig,win)
    chart.get_tk_widget().pack()

def agraph():
    win=Toplevel()
    win.geometry("1000x250")
    win.resizable(False,False)
    win.title("Graph of Active Cases")
    win.configure(background="#3BF6E4")
    x=df["State_code"]
    y=df["Active"]
    fig=plt.Figure(figsize=(50,50),dpi=100)
    fig.add_subplot(111).bar(x,y)
    chart=FigureCanvasTkAgg(fig,win)
    chart.get_tk_widget().pack()

def dgraph():
    win=Toplevel()
    win.geometry("1000x250")
    win.resizable(False,False)
    win.title("Graph of Deaths")
    win.configure(background="#3BF6E4")
    x=df["State_code"]
    y=df["Deaths"]
    fig=plt.Figure(figsize=(50,50),dpi=100)
    fig.add_subplot(111).bar(x,y)
    chart=FigureCanvasTkAgg(fig,win)
    chart.get_tk_widget().pack()

def x():
    choose = StringVar()
    choose.set("Choose which state do u want to know about:")
    directionlb = Label(root,textvariable = choose)
    directionlb.configure(background="#57F552")
    directionlb.pack()
    # the text to show graphs
    choose = StringVar()
    choose.set("GRAPHS: State code wise")
    directionlb = Label(root,textvariable = choose)
    directionlb.configure(background="#3BF6E4")
    directionlb.place(x=600,y=400)
    x=Button(root,text="MAHARASHTRA",command=Maharashtra,width=15,bg="#57F552")
    x.place(x=2,y=275)
    x=Button(root,text="Tamil Nadu",command=tamilnadu,width=15,bg="#57F552")
    x.place(x=2,y=300)
    x=Button(root,text="Delhi",command=delhi,width=15,bg="#57F552")
    x.place(x=2,y=325)
    x=Button(root,text="Gujarat",command=gujrat,width=15,bg="#57F552")
    x.place(x=2,y=350)
    x=Button(root,text="Karnatka",command=karnatka,width=15,bg="#57F552")
    x.place(x=2,y=375)
    x=Button(root,text="Uttar Pradesh",command=up,width=15,bg="#57F552")
    x.place(x=2,y=400)
    x=Button(root,text="Telangana",command=telangana,width=15,bg="#57F552")
    x.place(x=2,y=425)
    x=Button(root,text="Andhra Pradesh",command=andhrapradesh,width=15,bg="#57F552")
    x.place(x=2,y=450)
    x=Button(root,text="West Bengal",command=wb,width=15,bg="#57F552")
    x.place(x=2,y=475)
    x=Button(root,text="Rajasthan",command=rajasthan,width=15,bg="#57F552")
    x.place(x=2,y=500)
    x=Button(root,text="Haryana",command=haryana,width=15,bg="#57F552")
    x.place(x=2,y=525)
    x=Button(root,text="Bihar",command=bihar,width=15,bg="#57F552")
    x.place(x=2,y=550)
    x=Button(root,text="Madhya Pradesh",command=mp,width=15,bg="#57F552")
    x.place(x=2,y=575)
    x=Button(root,text="Assam",command=assam,width=15,bg="#57F552")
    x.place(x=2,y=600)
    x=Button(root,text="Odisha",command=odisha,width=15,bg="#57F552")
    x.place(x=2,y=625)
    x=Button(root,text="J&K",command=jk,width=15,bg="#57F552")
    x.place(x=200,y=275)
    x=Button(root,text="Punjab",command=punjab,width=15,bg="#57F552")
    x.place(x=200,y=300)
    x=Button(root,text="Kerala",command=kerala,width=15,bg="#57F552")
    x.place(x=200,y=325)
    x=Button(root,text="Chattisgarh",command=chattisgarh,width=15,bg="#57F552")
    x.place(x=200,y=350)
    x=Button(root,text="Jharkhand",command=jharkhand,width=15,bg="#57F552")
    x.place(x=200,y=375)
    x=Button(root,text="Uttarakhand",command=uttarakhand,width=15,bg="#57F552")
    x.place(x=200,y=400)
    x=Button(root,text="Goa",command=goa,width=15,bg="#57F552")
    x.place(x=200,y=425)
    x=Button(root,text="State Unassigned",command=su,width=15,bg="#57F552")
    x.place(x=200,y=450)
    x=Button(root,text="Tripura",command=tripura,width=15,bg="#57F552")
    x.place(x=200,y=475)
    x=Button(root,text="Manipur",command=manipur,width=15,bg="#57F552")
    x.place(x=200,y=500)
    x=Button(root,text="Puducherry",command=puducherry,width=15,bg="#57F552")
    x.place(x=200,y=525)
    x=Button(root,text="Himachal",command=himachal,width=15,bg="#57F552")
    x.place(x=200,y=550)
    x=Button(root,text="Ladakh",command=ladakh,width=15,bg="#57F552")
    x.place(x=200,y=575)
    x=Button(root,text="Nagaland",command=nagaland,width=15,bg="#57F552")
    x.place(x=200,y=600)
    x=Button(root,text="Chandigarh",command=chandigarh,width=15,bg="#57F552")
    x.place(x=200,y=625)
    x=Button(root,text="D&D",command=DD,width=15,bg="#57F552")
    x.place(x=400,y=275)
    x=Button(root,text="Arunachal Pradesh",command=arunachal,width=15,bg="#57F552")
    x.place(x=400,y=300)
    x=Button(root,text="Meghalaya",command=meghalaya,width=15,bg="#57F552")
    x.place(x=400,y=325)
    x=Button(root,text="Mizoram",command=mizoram,width=15,bg="#57F552")
    x.place(x=400,y=350)
    x=Button(root,text="Andaman & NL",command=anl,width=15,bg="#57F552")
    x.place(x=400,y=375)
    x=Button(root,text="Sikkim",command=sikkim,width=15,bg="#57F552")
    x.place(x=400,y=400)
    x=Button(root,text="Lakshadweep",command=lk,width=15,bg="#57F552")
    x.place(x=400,y=425)
    x=Button(root,text="graph of conf.cases",command=cgraph,width=20,bg="#57F552")
    x.place(x=600,y=425)
    x=Button(root,text="graph of recov.cases",command=rgraph,width=20,bg="#57F552")
    x.place(x=600,y=450)
    x=Button(root,text="graph of active.cases",command=agraph,width=20,bg="#57F552")
    x.place(x=600,y=475)
    x=Button(root,text="graph of death.cases",command=dgraph,width=20,bg="#57F552")
    x.place(x=600,y=500)

# from which country
INDIA = StringVar()
INDIA.set("In INDIA")
directionlb = Label(root,textvariable = INDIA)
directionlb.configure(background="#3BF6E4")
directionlb.pack()

#to show confirmed patients
confirmed = StringVar()
confirmed.set("\nConfirmed till Now : {} ".format(state_csv["Confirmed"][0]))
directionlb = Label(root,textvariable = confirmed)
directionlb.configure(background="#3BF6E4")
directionlb.pack()

#to show active patients
Active = StringVar()
Active.set("\nActive till Now : {} ".format(state_csv["Active"][0]))
directionlb = Label(root,textvariable = Active)
directionlb.configure(background="#3BF6E4")
directionlb.pack()

#to show recovered patients
Recovered = StringVar()
Recovered.set("\n Recovered till Now : {}".format(state_csv["Recovered"][0]))
directionlb = Label(root,textvariable = Recovered)
directionlb.configure(background="#3BF6E4")
directionlb.pack()

#to show deaths
Active = StringVar()
Active.set("\nDeaths till Now : {} ".format(state_csv["Deaths"][0]))
directionlb = Label(root,textvariable = Active)
directionlb.configure(background="#3BF6E4")
directionlb.pack()

#if you eant to know about states status
Active = StringVar()
Active.set("\nDo want to know more about states type y/n:")
directionlb = Label(root,textvariable = Active)
directionlb.configure(background="#3BF6E4")
directionlb.pack()

opinion=Button(root,text="YES",command=x,width=15,bg="#57F552")
opinion.pack()
opinion=Button(root,text="No",command=root.destroy,width=15,bg="#57F552")
opinion.pack()

root.mainloop()
